### ISSUE TITLE
Bug on NR 3.1.0 running on Windows 11 ?

### ISSUE THREAD

**Issue by pizzabakker** [fellinga/node-red-contrib-ui-time-scheduler#97] opened 2023-12-08 10:05 UTC
Hi,

Node looks good, but has an error on NodeRed 3.1.0 running on my Windows 11 PC.
When ui-time-scheduler is used in a flow only ui-time-scheduler is shown in browser, all other disappear from the menu.
Happens in Edge and FireFox browser.

After deleting/disable Flow tab with ui-time-scheduler on it , nothing shows at all anymore.
Nodered has to be restarted to show other UI elements and menu items again.

Even in the provided sample , only ui-time-scheduler node is shown and switch node is gone ??
Also happens in Edge and FireFox browser.

Note: After disabling Tab wit your node on it and enabling it again only the switch shows.
![image](https://github.com/fellinga/node-red-contrib-ui-time-scheduler/assets/72464463/debbedfa-c750-4732-97dd-4475c5dc5057)

 After refresh F5 in browser menu items and switch is gone and it shows only your node ??
![image](https://github.com/fellinga/node-red-contrib-ui-time-scheduler/assets/72464463/c43eafa1-b38e-4d17-93ee-7c997a44b2d4)

Any ideas ?

**Comment by fellinga** [comment] 2023-12-08 14:29
My test system is currently on node-red 3.1.3 and i do not experience any problems.
Are you using the latest version of node-red-ui-time-scheduler and node-red-dashboard? Please check within the node-red menu / manage palette, it should look like this:
![image](https://github.com/fellinga/node-red-contrib-ui-time-scheduler/assets/26927863/37d2c419-a270-4209-8f54-c906b8f9a5e1)

**Comment by pizzabakker** [comment] 2023-12-14 10:22
Finally, found it : its a Windows thing :-(   and my mistake.

Problem with the Schedule Node occurs when NodeRed(Windows)  is started with the wrong path.
Real existing path = C:\Users\U1\.node-red

Starting Node-Red with the good parameter   -u C:\Users\U1\.node-red  --> Scheduler works in UI. All other Tabs are shown.
Starting Node-Red with the wrong parameter -u C:\Users\u1\.node-red  --> Scheduler is only Tab shown in UI.

Do not know if this is a NodeRed or a Schedule Node issue. 
Thing is that other Nodes can live with my 'typo' and are working fine as far as i can see ;-)

I hope you can enlighten me ?

**Comment by fellinga** [comment] 2023-12-30 11:28
I am not sure why the case would make a difference and since I am not using node-red on Windows I am not able to reproduce. Can you see any errors in the dev tools?

**Comment by pizzabakker** [comment] 2023-12-30 16:45
No big deal, It was my mistake, typing an "N" --> C:\Users\u1\.Node-red   instead of an "n" -->C:\Users\u1\.node-red 

Problem is caused by a relative path construction like ./ or ../ in a Node relying on the Node-Red internal path.
When NodeRed (Windows) is started with a parameter containing a non existing path --> -u C:\Users\u1\.Node-red ,
  NodeRed internal path defaults to the .\.node-red\node_modules\.bin path instead of the C:\Users\u1\.node-red  path.
  Therefore some things are presumably not read from the correct folder and some nodes behave different as expected.

Note: Windows itself is NOT case sensitive, Linux is. NodeRed on Windows seems to be Case Sensitive at least at startup.

For me the issue is 'fixed'

**Comment by fellinga** [comment] 2023-12-30 16:47
Thanks for the detailed feedback - it might help someone else in the future!
Going to close this issue now.

**Closed by fellinga** 2023-12-30 16:47 UTC
