### ISSUE TITLE
Possible issue of losing timers

### ISSUE THREAD

**Issue by scargill** [fellinga/node-red-contrib-ui-time-scheduler#12] opened 2020-11-24 19:15 UTC
I set up your timer to test - added file in and out, added a couple of devices and time ranges... stopped node-red, started node-red - NO problem. Kept the lot. Went into Node-Red, changed the SIZE if the scheduler (height) and it lost all the times.

I thought (think) this could make a useful addition to my NR arsenal along with node-red-contrib-bigtimer..... but did I just spot a bug or did I miss something?

Regards

Pete

**Comment by fellinga** [comment] 2020-11-24 19:29
I actually did that quite often today to test the new update and that did not happen to me. The only thing that I can imagine would be that you changed the size and to the event mode at the same time. The default timers are not compatible with the event mode timers and the event mode starts over with an empty schedule if the payload is not valid. 

Is that a possibility?

**Comment by scargill** [comment] 2020-11-24 20:22
> I actually did that quite often today to test the new update and that did not happen to me. The only thing that I can imagine would be that you changed the size and activated the event mode at the same time. The default timers are not compatible with the event mode timers and the event mode starts over with an empty schedule if the payload is not valid.
> 
> Is that a possibility?

Hi

I didn't use event mode. It is possible you updated the mode about the same time as I wsa trying this? But no I did nothing other than as described above.  If I hear nothing I'll happily try again tomorrow.

**Comment by fellinga** [comment] 2020-11-24 20:43
I can't reproduce it. It also seems to be quite unlikely - for clarification: redeploying destroys the node and all its data. Therefore without an incoming data after redeploying the node is definitely empty. To show data after a redeploy/restart you have to use an inject node like this:
![11](https://user-images.githubusercontent.com/26927863/100148562-36db0a80-2e9d-11eb-9c67-72f0ba4e7c17.png)

That leads to the following: if the data injected after a redeploy is valid, the node will display it. 
If you can somehow reproduce this issue I'd happy to investigate further.

**Comment by scargill** [comment] 2020-11-24 21:16
Thanks for the speedy response.

Different RPI(4) - virtually identical. I have as before, the inject after 0.1 secs. As before I have the "file input" node with a file name (/home/pi/ui-sched-test.txt). On the first output I have the "file" node - same file name. Set to overwrite - and not to create directory.
Again I added a time. Stopped node-red, started node-red - time is still there. Went into your node and adjusted the height in the "properties" "size" box.  Now, my one time setting is again lost.  Am I missing something obvious here?

Regards  Pete

**Comment by fellinga** [comment] 2020-11-24 21:43
Tried that on my Rpi3 just now works fine for me. What size did you pick?

Can you check if the file **ui-sched-test.txt** contains any data before you edit the node height - and if it contains data after deploying? You can also manually hit the inject button to see if the payload arrives at the node.

**Comment by scargill** [comment] 2020-11-25 08:54
Ok, just got up... checked node-red - timer is empty - but there is a line of timer info in ui-sched-test.txt
Hit the timestamp - that schedule is back in the UI. 
(I have 2 windows open in Chrome on the PC - one is Node-Red, the othrer is the GUI).

Flick to NR.  - the scheduler size is 5*7.
Change size to 6*8. Frploy.
Go back to UI which has now flicked back to my home UI page. Select the test page.
"Nothing planned yet"
Hit refresh - same result.
Go back to NR page -- hit the timestamp again.
REturn to UI - the schedule is back.....

repeat...

Something wrong, definitely.
![image](https://user-images.githubusercontent.com/1889411/100204286-fcf11f00-2f03-11eb-9613-84e40e70ce22.png)
![image](https://user-images.githubusercontent.com/1889411/100204346-0f6b5880-2f04-11eb-88f8-157c070e955d.png)

I've no idea if the images I am pasting to you are actually coming up as image - I just see text line starting ![image]

**Comment by fellinga** [comment] 2020-11-25 09:09
Okay that makes sense now. I did not think about it yesterday - but you are probably only deploying the **modified node**? Like so:
![Uploading 11.png…]()
Deploying the node only does not trigger the inject node -> therefore no timers are being injected. "**Modified Flow**" and "**Full**" should trigger the inject node. Please let me know if this helps.

**Comment by scargill** [comment] 2020-11-25 14:23
MODIFIED FLOW works a treat. Do you plan to keep expanding this? Months for example?

**Comment by fellinga** [comment] 2020-11-25 14:32
Glad to hear!
Haven't thought about adding months to be honest, but it is definitely a good idea... I'll add this to my backlog.

**Comment by scargill** [comment] 2020-11-25 15:01
> Glad to hear!
> Haven't thought about adding months to be honest, but it is definitely a good idea... I'll add this to my backlog.

I've a lot of experience of this... so for example, I might schedule my air conditioner to come on first thing in the morning for a while to take off the chill.  A HOLD button on the schedule would be good for thos weeks I'm not here - and months would let me set rough winter and summer times.  Thinking about it, one nice optional dial below and you;re half way to a decent thermostat :-)  Out of interest here's how far I took mine (in daily use).

![image](https://user-images.githubusercontent.com/1889411/100244672-82da8d80-2f37-11eb-987a-1fc801764c4c.png)

**Comment by fellinga** [comment] 2020-11-26 10:25
Looks pretty nice! I'll think about your suggestions, and we'll see how far this node can go.
I'll close this issue for now, If you need anything else, let me know!

**Closed** 2020-11-26 10:26 UTC
Labels: good first issue
