### ISSUE TITLE
Sun events

### ISSUE THREAD

**Issue by MiMoertel** [fellinga/node-red-contrib-ui-time-scheduler#47] opened 2021-07-02 09:56 UTC
Hi, nice work.

one things would be nice.
a mix of sun events and fixed Time in one schedule

thanks for considering

**Comment by fellinga** [comment] 2021-07-02 10:00
Duplicate of #33.

Please use event mode if you need different start&end types.

**Closed by fellinga** 2021-07-02 10:00 UTC
